//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovyGorodAsp.Resources.Views.Home {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NovyGorodAsp.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string about_us {
            get {
                return ResourceManager.GetString("about-us", resourceCulture);
            }
        }
        
        internal static string company_name {
            get {
                return ResourceManager.GetString("company-name", resourceCulture);
            }
        }
        
        internal static string company_summary {
            get {
                return ResourceManager.GetString("company-summary", resourceCulture);
            }
        }
        
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        internal static string more_about_projects {
            get {
                return ResourceManager.GetString("more-about-projects", resourceCulture);
            }
        }
        
        internal static string theatre {
            get {
                return ResourceManager.GetString("theatre", resourceCulture);
            }
        }
        
        internal static string theatre_summary {
            get {
                return ResourceManager.GetString("theatre-summary", resourceCulture);
            }
        }
        
        internal static string more_about_theatre {
            get {
                return ResourceManager.GetString("more-about-theatre", resourceCulture);
            }
        }
        
        internal static string school_and_festivals {
            get {
                return ResourceManager.GetString("school-and-festivals", resourceCulture);
            }
        }
        
        internal static string school_and_festivals_summary {
            get {
                return ResourceManager.GetString("school-and-festivals-summary", resourceCulture);
            }
        }
        
        internal static string more_about_school {
            get {
                return ResourceManager.GetString("more-about-school", resourceCulture);
            }
        }
        
        internal static string work_direction {
            get {
                return ResourceManager.GetString("work-direction", resourceCulture);
            }
        }
    }
}
