name: Solution/Build and Test

on:
  pull_request:
    branches:
      - master
      - release/*
      - develop

jobs:
  Job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build solution
        run: dotnet build --configuration Release