name: Web App / Deploy

on:
  workflow_dispatch:
    inputs:
      build_version:
        type: string
        description: 'Version of web application artifact: (major).(minor)'
        required: true

env:
  ARTIFACT_NAME: novy-gorod-web-app_${{ inputs.build_version }}

jobs:
  Job:
    runs-on: windows-latest
    environment: prod
    steps:
      - name: Download artifact '${{ env.ARTIFACT_NAME }}'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: web-app.build.yml
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact

      - name: Create file '.env'
        shell: bash
        run: |
          echo "CONNECTIONSTRINGS__MSSQL=${CONNECTIONSTRINGS__MSSQL}" >> artifact/.env
          
      - name: Create file 'ftp_commands.txt'
        shell: bash
        run: |
          echo "CONNECTIONSTRINGS__MSSQL=${CONNECTIONSTRINGS__MSSQL}" >> ftp_commands.txt
          
      - name: Deploy artifact
        shell: bash
        run: |
          ftp
          open
          
      