name: Web App/Build 

on:
  workflow_dispatch:
    inputs:
      build_version:
        type: string
        description: 'Version of web application: (major).(minor)'
        required: true
  push:
    tags: release/v*
    paths:
      - src

env:
  BUILD_VERSION: ${{ inputs.build_version }}

jobs:
  Job:
    runs-on: windows-latest
    steps:      
      - name: Set build version from tag name
        if: ${{ !env.BUILD_VERSION }}
        shell: bash
        run: echo "BUILD_VERSION=${GITHUB_REF_NAME##*v}" >> $GITHUB_ENV
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3

      - name: Build project
        shell: bash
        run: dotnet build src/Presentation/NovyGorodAsp --configuration Release -p:Version=${BUILD_VERSION}

      - name: Invoke NpmInstallAndMove.ps1
        run: .\scripts\NpmInstallAndMove.ps1

      - name: Publish artifact
        run: dotnet publish src/Presentation/NovyGorodAsp --output web-app --no-build --configuration Release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: novy-gorod-web-app_${{ env.BUILD_VERSION }}
          path: web-app/**
          if-no-files-found: error